"""add user model

Revision ID: d5bc80d01630
Revises:
Create Date: 2026-04-19 21:35:56.391636

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d5bc80d01630"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),  # ty:ignore[possibly-missing-submodule]
        sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),  # ty:ignore[possibly-missing-submodule]
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),  # ty:ignore[possibly-missing-submodule]
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###
