name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: "3.12"

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        id: setup-uv
        uses: astral-sh/setup-uv@v7
        with:
          activate-environment: true
          enable-cache: true

      - name: Install dependencies
        run: |
          uv pip install pre-commit pip-audit

      - name: Cache pre-commit
        uses: actions/cache@v5
        with:
          path: ~/.cache/pre-commit
          key: precommit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit
        run: uv run pre-commit run --all-files

      - name: Check vulnerabilities
        run: uv run pip-audit

