name: Pytest

on: [push]

env:
  PYTHON_VERSION: "3.12"
  UV_SYSTEM_PYTHON: 1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        id: setup-uv
        uses: astral-sh/setup-uv@v7
        with:
          activate-environment: true
          enable-cache: true

      - name: Install requirements
        run: uv sync

      # - name: Test with pytest
      #   run: |
      #     uv run pytest -vv

      - name: Run tests with coverage
        run: |
          uv run pytest --cov=src --cov-report=xml --cov-report=html

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
